theme: jekyll-theme-time-machine



<!DOCTYPE html>

<html>

<head>

<meta charset='utf-8'>

<meta http-equiv="X-UA-Compatible" content="chrome=1">

<meta name="viewport" content="width=640" />



<link rel="stylesheet" href="stylesheets/core.css" media="screen"/>

<link rel="stylesheet" href="stylesheets/mobile.css" media="handheld, only screen and (max-device-width:640px)"/>

<link rel="stylesheet" href="stylesheets/pygment_trac.css"/>



<script type="text/javascript" src="javascripts/modernizr.js"></script>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<script type="text/javascript" src="javascripts/headsmart.min.js"></script>

<script type="text/javascript">

$(document).ready(function () {

$('#main_content').headsmart()

})

</script>

<title>Keeps it Floating by Terry McCart</title>

</head>



<body>

<a id="forkme_banner" href="https://github.com/tmtrademarked/keepitfloating”>View on GitHub</a>

<div class="shell">



<header>

<span class="ribbon-outer">

<span class="ribbon-inner">

<h1>Keep it Floating</h1>



</span>

<span class="left-tail"></span>

<span class="right-tail"></span>

</span>

</header>

















<span class="banner-fix"></span>





<section id="main_content">

<p><strong>Keep it Floating  </strong></p>







<ul>

<li>Keep it floating is a basic  game for an iPhone.</li>

<li>You tap on the ball to keep it in the air. The more taps the faster the ball goes.</li>



  




















<p>If you want to test apps, here is what you need you to do:</p>



<p>1) Download and Install UDID Profile App (Free) to your iPhone, iPad, or iTouch.</p>



<p><a href="http://get.udid.io/">http://get.udid.io/</a></p>



<p>2) After installed, Run to get UDID</p>



<p>3) Click the "Send Email" button</p>



<p>4) Send email to: <a href="mailto:mccart.terry@gmail.com”>mccart.terry@gmail.com</a></p>







</section>



<footer>

<span class="ribbon-outer">

<span class="ribbon-inner">



</span>

<span class="left-tail"></span>

<span class="right-tail"></span>

</span>

<p>Generated with <a href="http://pages.github.com">GitHub Pages</a> using Merlot</p>

<span class="octocat"></span>

</footer>



</div>





</body>

</html>


