theme: jekyll-theme-time-machine

title: "Keep it Floating: A Physics Game"

body: "Keep it Floating is a basic physics game. You tap a ball and it floats into the air. Touch it before it hits the bottom of the screen and you get a point. The more you tap it the faster the ball moves."
